# Generated by Django 4.2.4 on 2023-08-09 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('serial_number', models.CharField(help_text='Certificate serial number', max_length=8, unique=True, verbose_name='Serial number')),
                ('type', models.SmallIntegerField(choices=[(1, 'jismoniy'), (2, 'yuridik')], help_text='Key type: 1-jismoniy, 2-yuridik', verbose_name='Key type')),
                ('file', models.FileField(help_text='Certificate file', unique=True, upload_to='', verbose_name='Certificate file')),
                ('password', models.CharField(help_text='Password of certificate', max_length=15, verbose_name='Password')),
                ('name', models.CharField(help_text='Name of the certificate holder', max_length=100, verbose_name='Name')),
                ('surname', models.CharField(help_text='Surname of the certificate holder', max_length=100, verbose_name='Surname')),
                ('full_name', models.CharField(help_text='Full name of the certificate holder', max_length=255, verbose_name='Full name')),
                ('jshshir', models.PositiveIntegerField(help_text='Personal Identification Number of an Individual', verbose_name='JSHSHIR')),
                ('valid_from', models.DateTimeField(help_text='Date of validity of the certificate', verbose_name='Valid from datetime')),
                ('valid_to', models.DateTimeField(help_text='Until what date is the certificate valid', verbose_name='Valid to datetime')),
                ('location', models.CharField(help_text='Location of certificate holder', max_length=100, verbose_name='Location')),
                ('city', models.CharField(help_text='City of certificate holder', max_length=100, verbose_name='City')),
                ('country', models.CharField(help_text='Country of certificate holder', max_length=100, verbose_name='Country')),
                ('stir', models.PositiveIntegerField(blank=True, help_text='Taxpayer identification number', null=True, verbose_name='STIR')),
                ('organization', models.CharField(blank=True, help_text='Organization name', max_length=150, null=True, verbose_name='Organization')),
                ('employee_type', models.CharField(blank=True, help_text='Employee type: Director/Manager/worker...', max_length=50, null=True, verbose_name='Employee type')),
                ('ou', models.CharField(blank=True, help_text='higher organization', max_length=100, null=True, verbose_name='OU')),
                ('business_category', models.CharField(blank=True, help_text='Business category', max_length=100, null=True, verbose_name='Business category')),
                ('uid', models.PositiveIntegerField(blank=True, help_text='Unique ID', null=True, verbose_name='UID')),
            ],
        ),
    ]
