# Generated by Django 4.2.4 on 2023-08-11 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eimzo', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='key',
            unique_together={('stir', 'uid')},
        ),
    ]
